### ISSUE TITLE
About map grid_conf

### ISSUE THREAD

**Issue by ahyunSeo** [Bin-ze/BEVFormer_segmentation_detection#7]
Hi,

Thank you for your nice implementation. I was looking for this!
I wonder how you get the numbers of map [grid_conf](https://github.com/Bin-ze/BEVFormer_segmentation_detection/blob/master/projects/configs/bevformer/bevformer_small_seg_det.py#L29).
I believe in LSS they used [-50, 50]
Did you intentionally set the grid_conf of detection and segmentation different?

Thanks in advance.
Ahyun

**Comment by Bin-ze** [comment]
1. The segmentation map in LSS is different from this segmentation map, it contains more categories, so there is more supervised information for training
2. If only the lane lines and road boundaries are divided, then the supervision information is insufficient, so it is necessary to choose a smaller area as much as possible, such as -30, 30, which roughly meets the width of the road, so this choice is more reasonable, compared to -50, at 50, most of the area will be blank
3. In order to compare with hdmapnet and beverse algorithms, this configuration is selected, but it also supports modifying the configuration file to expand the perception range
ask for a star！aoligei

**Comment by ahyunSeo** [comment]
Thanks a lot!
